# Generated by Django 5.0.7 on 2024-07-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applic", "0003_remove_cartitem_cart_pokupka_delete_cart_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokupka",
            name="pokupka_date",
            field=models.DateTimeField(),
        ),
    ]
