# Generated by Django 5.0.7 on 2024-07-16 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applic", "0004_alter_pokupka_pokupka_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Pokupka",
        ),
    ]
