# Generated by Django 5.0.7 on 2024-07-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applic", "0005_delete_pokupka"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
